### ISSUE TITLE
Make route lines and stop info optional

### ISSUE THREAD

**Issue by sgdoerfler** [rectangle-dbmi/Realtime-Port-Authority#114]
My cellular plan gives me a limited amount of data. I'd like to spend it only on info I really need. I rarely need to see the bus route or the stop locations; I already know those for most buses I take. Mostly I just need to see the real-time bus locations.

So could all that often-extraneous info be made optional? Or perhaps optional if the current connection is cellular, not Wifi? (Maybe a radio button control like "Display bus routes: ( ) Always (*) Wifi only ( ) Never".)

**Comment by epicstar** [comment]
Will not fix this... We will save the patterns to storage (https://github.com/rectangle-dbmi/Realtime-Port-Authority/pull/149). Take note that this will solve some startup problems too.

Also, each pattern xml is only 45 KB....
