### ISSUE TITLE
Make bus icons easier to spot

### ISSUE THREAD

**Issue by toddmedema** [rectangle-dbmi/Realtime-Port-Authority#116]
Right now, their arrow shape blends in with roads too easily (especially curvy roads). Would be useful to switch to something entirely different, like a black and white bus icon (would also solve some of the color blind issues)

**Comment by epicstar** [comment]
Now that certain bugs are fixed, I may be able to work on this issue here... If you have suggestions, please tell us! We need more devices with different screen sizes to get this going. Also, the bus stop icons are really lazy but I'd like to be able to make them look better at some point.

**Comment by toddmedema** [comment]
The simplest suggestion I can think of would be to fill in the triangle. Really, the goal in my head is that it shouldn't just be two lines, because that blends in with the roads (which are also lines) too easily. The arrows make the direction easy to discern, which is important info, so the Google Maps "circle as location" paradigm doesn't work here (just had a funny idea for an April Fool's joke, where all of the bus icons are replaced with the USS Enterprise) 

A good source I use for icons is The Noun Project (it's only like $2 for an icon) - http://thenounproject.com/search/?q=bus

Another way to help differentiate the icons might be a bit of drop shadow to add some depth? Or even just making the arrows thicker, so that the arrow width isn't the same as the road width.

**Comment by epicstar** [comment]
Alright, so I'm going to soon revisit this part. Hopefully I am not lazy enough to do this... I'm thinking of moving the bus stop icons towards [circles](https://developers.google.com/maps/documentation/android/shapes#circles). This way, I can think of another way that isn't an infowindow to display ETAs. I'll also use one bus icon which will be filled in via colorfilter (as of right now, we're using 92 icons for 92 buses....................... ..........)

**Comment by epicstar** [comment]
[Here](http://blog.danlew.net/2014/08/18/fast-android-asset-theming-with-colorfilter/) is more info on "dynamic" color icons....... I'd have to use an O(1) implementation to get the bus route colors by the route name, but I'm not sure how much bigger the app will be at runtime as a result of it.

**Comment by epicstar** [comment]
Proposal 1....

http://i.imgur.com/zEIA2dx.png

**Comment by epicstar** [comment]
Wow.. so bad... Proposal 2:

http://i.imgur.com/DK6H4cE.png

**Comment by toddmedema** [comment]
I like proposal 2

**Comment by RitwikGupta** [comment]
Same

**Comment by epicstar** [comment]
This is what the ![new icons look like](http://i.imgur.com/L8UnF74.png) so far. Bros, let me know what you think. I also want screenshots from other people, too.

**Comment by epicstar** [comment]
Here's a less flattering pic with the bus stops....

![Imgur](http://i.imgur.com/cWuT0jY.png)

**Comment by sgdoerfler** [comment]
The new icons look nice, but when I tap on one, its infobox goes away as soon as the bus icon moves. Sometimes this happens a second after ti appears, sometimes it lasts longer. Ideally, when a bus moves, its infobox would just shift to the new location instead of disappearing.

Also, the infobox has a missing space after some ")" and before some "(" characters. (I thought I reported this previously and you fixed it, so maybe this is a regression.)

Also, the new bus icon sometimes appears on top of the bus stop icons, and sometimes underneath it. I think it should always be on top. (It might be nice if it were just transparent enough that you could still see there was a bus stop icon underneath, but not so much that it interfered with reading the route number.)

**Comment by epicstar** [comment]
> The new icons look nice, but when I tap on one, its infobox goes away as soon as the bus icon moves. Sometimes this happens a second after ti appears, sometimes it lasts longer. Ideally, when a bus moves, its infobox would just shift to the new location instead of disappearing.

I'll what I can do on this.

> Also, the infobox has a missing space after some ")" and before some "(" characters. (I thought I reported this previously and you fixed it, so maybe this is a regression.)

Will fix T_T

> Also, the new bus icon sometimes appears on top of the bus stop icons, and sometimes underneath it. I think it should always be on top. (It might be nice if it were just transparent enough that you could still see there was a bus stop icon underneath, but not so much that it interfered with reading the route number.)

From what I know, there's no way to put markers on top of each other programmatically as there's no z-axis. However, if I turn the bus stops into the circle polygon, it'll be possible. Even better... it'll look nicer, too.
