### ISSUE TITLE
Position info box above and centered on bus icon

### ISSUE THREAD

**Issue by sgdoerfler** [rectangle-dbmi/Realtime-Port-Authority#126]
Running 2.93B. The info box that appears when clicking on a bus stop is positioned perfectly, but the one that appears when clicking on a bus isn't. For a southbound bus, it completely covers the bus icon. For an eastbound bus, it's positioned to the right of the icon; for a westbound bus, to the left. When multiple buses are close by, it's a bit confusing to tell if you've successfully tapped on the bus you want, since the info box can be pointing to a different bus.

I think the info box should be positioned so its "point" is at a spot just above the top center of the bus icon, no matter which way the bus is pointing (similar to how it's positioned for bus stops).

**Comment by epicstar** [comment]
apparently because of issue https://github.com/rectangle-dbmi/Realtime-Port-Authority/issues/158, we should look into getting better bus icons...
