### ISSUE TITLE
No route lines when connectivity returns

### ISSUE THREAD

**Issue by sgdoerfler** [rectangle-dbmi/Realtime-Port-Authority#138]
Go to airplane mode, then start the app. You get a map, but no RT info of course. Now leave airplane mode. The bus icons appear on the map after a few seconds, but the route lines do not, even waiting several minutes. Rotating the device to change its orientation makes them come back. 2.95B.

I also saw the missing-route-lines issue once after the device had powered down due to inactivity, but haven't been able to reproduce that case.

**Comment by epicstar** [comment]
Route calls should be reduced using https://github.com/rectangle-dbmi/Realtime-Port-Authority/pull/149.... Please report issues if there are problems in 3.2 (beta)

**Comment by sgdoerfler** [comment]
As expected, in 3.2 it's now harder to make this bug show up. New steps are:
1. Switch to Airplane mode (or otherwise lose connectivity).
2. Clear Transit, then select some routes.
3. Restore connectivity.

The bus icons then appear, but the route lines and stops do not. Switching to the home screen and back to the app makes them appear.

**Comment by epicstar** [comment]
I can only fix this atm by pressing "Clear Transit" and then selecting the route lines when internet activity is restored. I will make a new method to close the whole app when there's no internet but for now, I'll leave it as is...

**Comment by sgdoerfler** [comment]
I'm not sure forcing the app to exit would be better than the current behavior, where I can always manually exit and restart the app. It's happened that the app gets some info I care about, and then while it's trying to retrieve some other info (say, list of stops for a route that might even be off the map now), I move out of range of the Wifi signal and get the message at the bottom that there's a problem. Right now, I can use the data it managed to retrieve successfully. Forcing the app to quit at that point would lose whatever data it's already retrieved.

I suggest just leaving it alone, unless you can find a way to have the routes update once the network comes back up. (But it might be OK if "network is now back up" caused the app to reload itself.)

**Comment by epicstar** [comment]
It'd be very possible to do that, but I would have to re-make the whole "retrieve route lines" task to use volley. It'll be an interesting task..........

**Comment by epicstar** [comment]
Don't think the fix will be a fix in this sense...

**Comment by epicstar** [comment]
Going to reopen this issue. I got this working with bus updates, so I'm going to do the same mechanism for the route lines.

**Comment by epicstar** [comment]
This is a direct cousin of #267 and requires #196

**Comment by epicstar** [comment]
I'm actually going to close this issue now. We can actually improve the app via #301. It won't make it to the 8.0.0 release but the current behavior without fixing this issue is already what we have right now.

**Comment by epicstar** [comment]
@sgdoerfler, this issue is going to be fixed in #316.

**Comment by epicstar** [comment]
Released with 8.0.0b3. Thanks @sgdoerfler for bringing up this issue.
