### ISSUE TITLE
Spaces in text shown in dialogs

### ISSUE THREAD

**Issue by sgdoerfler** [rectangle-dbmi/Realtime-Port-Authority#140]
The text in dialogs sometimes omits spaces from where they'd normally appear in text. For instance, the bus dialog's title omits a space between the route number and the "(" that follows it. The list of stops omits the space between the ")" and stop name that follows it. Finally, in that list, there's sometimes a space between the colon and the time that follows it, but sometimes there isn't. (Maybe it's trying to do something with tab stops?) In 2.95B. It would look better with spaces at these points.

**Comment by epicstar** [comment]
Ah... just saw this now...
