### ISSUE TITLE
Rotating device forgets zoom level

### ISSUE THREAD

**Issue by sgdoerfler** [rectangle-dbmi/Realtime-Port-Authority#150]
When I rotate my device 90 degrees, the map zooms far out so all route lines are entirely visible. When I rotate it back to its original orientation, it stays zoomed out. It should retain the zoom level on rotation.

In particular, returning the rotation to its original orientation should return the display to showing exactly what it was originally showing (since it's easy to accidentally change the orientation briefly).

**Comment by epicstar** [comment]
I acknowledge this 100% but I'll have to trace where my zoom levels are saved...

**Comment by epicstar** [comment]
This is fixed here https://github.com/rectangle-dbmi/Realtime-Port-Authority/pull/155. Right now, this is fixed in version number 3.30. If it's all good or if there are any more problems, please reply.

**Comment by epicstar** [comment]
I found out that variables save in onPause, so I now am able to keep the location of the camera when alt tabbing out of Maps..... https://github.com/rectangle-dbmi/Realtime-Port-Authority/pull/156

**Comment by sgdoerfler** [comment]
Working perfectly in version 3.32. Thanks!
