### ISSUE TITLE
Slow Load Up Time

### ISSUE THREAD

**Issue by epicstar** [rectangle-dbmi/Realtime-Port-Authority#151]
From what I've seen, it affects Samsung devices with touchwiz (omg please why). I haven't had this with my HTC One M7 (Converted to GPE), my brother's GPE LG G Pad, nor any Nexus 5's I've seen (these are the devices I see all the time). Ritwik has an S4 and has issues with the slowness. I'm wondering if there are any other slowness issues with other phones post-3.2.

**Comment by epicstar** [comment]
Notice some unsync issues with bloated phones (I'm looking at you samsung....) but slow loading is pretty much gone.

**Comment by epicstar** [comment]
I don't see it anymore with phones I've handled post-fix

**Comment by RitwikGupta** [comment]
Might be something with Xposed Framework or Zygote
