### ISSUE TITLE
import rectangledbmi.com.pittsburghrealtimetracker.hidden.PortAuthorityAPI is not found

### ISSUE THREAD

**Issue by juliezhoucmu** [rectangle-dbmi/Realtime-Port-Authority#177]
I can't locate this class, looks like it is ignored :
import rectangledbmi.com.pittsburghrealtimetracker.hidden.PortAuthorityAPI;

can you help to upload this one?

It is very important for me, thanks !

**Comment by epicstar** [comment]
Yes... it's ignored on purpose.... We'll think about fixing it but this is a more of a DDOS prevention for the main app

**Comment by epicstar** [comment]
EDIT: I'll keep this up, so please read the edited LICENSE. Thank you!!

**Comment by juliezhoucmu** [comment]
Sorry, I overlooked that 

Maybe we can put the [LICENSE](https://github.com/rectangle-dbmi/Realtime-Port-Authority/blob/b3b82bf6792d7dd808209c83d8fd7cd6924210cc/LICENSE) as a link in README, so that people who is as thoughtless as me will notice that :P

Anyway, thanks for the sharing,  I can get this running now  :)
