### ISSUE TITLE
Move Backend away from ASyncTask

### ISSUE THREAD

**Issue by epicstar** [rectangle-dbmi/Realtime-Port-Authority#180]
............. ASyncTask is so bad...... There are 3 big uses to the app and ASyncTask:
- retrieve bus data from PAT with TimerTask (ALSO BAD!!!)
- retrieve bus stop and bus pattern data from either the data folder or from PAT
- retrieve predictions data from PAT

Perhaps maybe we should look into using json data? Maybe this will be a good thing to look at as it will save data and there are also standard parsers for this (XML surprisingly has less useful ones)

**Comment by RitwikGupta** [comment]
JSON is awesome to use

**Comment by epicstar** [comment]
huehuehue

**Comment by epicstar** [comment]
http://stablekernel.com/blog/replace-asynctask-asynctaskloader-rx-observable-rxjava-android-patterns/

**Comment by epicstar** [comment]
Example of turning one of our asynctasks to rx observable...

https://www.youtube.com/watch?v=k3D0cWyNno4

**Comment by epicstar** [comment]
RIP TimerTask...

https://youtu.be/k3D0cWyNno4?t=46m1s

**Comment by epicstar** [comment]
Part one done
