### ISSUE TITLE
Bus Route Ordering

### ISSUE THREAD

**Issue by VincentIII** [rectangle-dbmi/Realtime-Port-Authority#192]
Bus Routes should be in corrected order.  Right now its 1, 12, 13, 14...., when it should be 1, 2, 3, 4....  This is also visible on the P lines

**Comment by epicstar** [comment]
@RitwikGupta actually suggested we do this back then before all the routes were in. This isn't really a challenging thing to do but it will take manual labor which we'll do kekeke

**Comment by RitwikGupta** [comment]
No manual labor is required. It just takes a `sort` call on the array

**Comment by epicstar** [comment]
Well.. actually.... Here are a bunch of issues with calling a normal sort....

1. if we do a normal `Arrays.sort(busNumbers)`, we get into an issue where it will just return the same order as it was. PAT actually gives us the info straight in "String" order. [This](http://stackoverflow.com/questions/785309/how-to-sort-integer-strings) question explains the issue in detail. The normal sort() method isn't number-aware. `"100A" < "9B"` in a string sort
2. We actually represent the list in an array via [strings.xml](https://github.com/rectangle-dbmi/Realtime-Port-Authority/blob/master/Android/Pittsburgh_Realtime_Tracker/app/src/main/res/values/strings.xml#L6). It's then brought together [here in the NavigatoinDrawerFragment](https://github.com/rectangle-dbmi/Realtime-Port-Authority/blob/master/Android/Pittsburgh_Realtime_Tracker/app/src/main/java/rectangledbmi/com/pittsburghrealtimetracker/NavigationDrawerFragment.java#L175)

The solutions I foresee we do...

- Make a comparable for the Route object and sort when the app boots up. We will have to use a derivation of [this](http://blog.icodejava.com/261/how-to-sort-alpha-numeric-strings-in-java/) into our comparable, which is a number-aware sort in java.
    - pros: we don't do too much work
    - cons: what was now an O(N) creation of the bus list would become O(N log N). Right now our N = 92 bus routes out of 98. Not too bad..... but it will still increase the bootup time as well as reduce battery life

I think it's better that we probably get this info ourselves, sort it with a number-aware sort, then we copy paste the results back to strings.xml in the new sorted format. It's some extra work for us, but at least the bootup time is preserved. What do you think?

**Comment by RitwikGupta** [comment]
The easiest and simplest way to do this is to remove the letters from each bus name, parse to int, then sort, then add the letters back.

**Comment by RitwikGupta** [comment]
```java
public static Comparator<Contact> COMPARE_BY_NAME = new Comparator<String>() {
        public int compare(String one, String other) {
            // Regex strip the letters away from one and two
            // Convert one and two to Integer
            return oneAsIntegerObject.compareTwo(twoAsIntegerObject)
        }
    };

// ... later on

Collections.sort(listOfBusNames, COMPARE_BY_NAME);

```

**Comment by sgdoerfler** [comment]
The code just posted seems to say, if the integer portion of two bus numbers differs, compare only that integer portion, else compare the whole string. That fails on examples like G31 vs P10. [This page](http://www.davekoelle.com/alphanum.html) seems to have a working algorithm in various languages. (It might be the same as epicstar's blog link, but I found the blog was blocked by some ad server junk.)

**Comment by RitwikGupta** [comment]
Good point. I wrote that real quick in ten seconds, without much thought. We should first compare the letters, then the numbers.

**Comment by sgdoerfler** [comment]
If you compare letters and numbers separately, you can run into problems with prefix letters vs suffix letters. For instance, you might put 28X after G2 since X comes after G. I think you should just use the working algorithm already linked, rather than trying to slap something together. The problem is a bit subtle.

**Comment by epicstar** [comment]
This is done and dusted.
