### ISSUE TITLE
Add Fabric to the App

### ISSUE THREAD

**Issue by epicstar** [rectangle-dbmi/Realtime-Port-Authority#268]
I feel the app bug crasher isn't good enough with Android's Play Store... as crash reports are voluntary. This means we can miss big bugs. [Fabric](https://get.fabric.io/) (which is pretty much Crashlytics) will give us what we want with better crash reports.

**Comment by nisrulz** [comment]
if this is still open can i work on this ?

**Comment by RitwikGupta** [comment]
Yeah, of course! Please feel free to propose any changes :)

**Comment by epicstar** [comment]
No
