### ISSUE TITLE
3 Line Button Does not Do Anything 

### ISSUE THREAD

**Issue by epicstar** [rectangle-dbmi/Realtime-Port-Authority#275]
Should be opening the bus drawer instead. Have to look into NavigationDrawerFragment.java

**Comment by mikeantonacci** [comment]
Looks like the problem happens in onOptionsItemSelected(MenuItem item)...

The itemId that gets passed in when you touch the hamburger button doesn't match anything, so nothing happens...

**Comment by epicstar** [comment]
oh kek

**Comment by epicstar** [comment]
Done with https://github.com/rectangle-dbmi/Realtime-Port-Authority/commit/389b3c7efb0deb0718b338d40599194b7e60a1af
