### ISSUE TITLE
New Routes and Stops Freshly Called from Internet Mid-App Session Will Not Appear Until App Restart

### ISSUE THREAD

**Issue by epicstar** [rectangle-dbmi/Realtime-Port-Authority#294]
#292 introduced a hidden bug where, if "Clear Route Cache", unselect, then reselect a previously selected route, the old route and stops info for that route will still be showing... until an app restart.

Ideally, this "Clear Route Cache" button shouldn't be here, but it is because currently, the observers that change the UI state of polylines and stops on the map are the only entities that need to know whether or not to uncache polylines and stops from BusMapFragment.

**Comment by epicstar** [comment]
We probably want to move all our cache logic in PatternDataManager. I made that class just for that purpose

**Comment by mikeantonacci** [comment]
I can take a look this weekend.  Probably we can use the idea from #276 here to avoid creating the need for the refresh button.

**Comment by epicstar** [comment]
Released with 8.0.0b3
