### ISSUE TITLE
Needs a better app icon 

### ISSUE THREAD

**Issue by toddmedema** [rectangle-dbmi/Realtime-Port-Authority#314]
Perhaps a bus? Right now it looks like nothing, is unnecessarily difficult to visually find amongst other apps

**Comment by TheAndroidMaster** [comment]
This is a duplicate of #204. We've been working on a new one for a while, but haven't come up with anything that good yet.

**Comment by epicstar** [comment]
As @TheAndroidMaster said, this is a duplicate of #204. Closing this now.
