### ISSUE TITLE
Icon/Logo Design Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [rectangle-dbmi/Realtime-Port-Authority#325]
Hi @epicstar , I am a graphic designer and i want to contribute to your project by proposing an Icon/Logo design. If you like and considered using this I will send you the needed files as a gift for free. Here is the layout of the design Sir.

I created a clean, modern and minimal design for the project. i hope you like it!

![idea](https://user-images.githubusercontent.com/36028424/39622004-417b5500-4fc3-11e8-8de5-8d10dfea95ce.png)

![presentation](https://user-images.githubusercontent.com/36028424/39621881-da4702d0-4fc2-11e8-9b5b-e9f7b50709ab.png)

If you like or have any suggestions just let me know and I will edit it.

Thanks and Best regards Sir,
-Tobaloidee

**Comment by epicstar** [comment]
I like it a lot. I had promised to change my icon to @balagikandasamy 's however which I haven't done yet (https://github.com/rectangle-dbmi/Realtime-Port-Authority/issues/204#issuecomment-310109005).

Let me talk about this internally before I engage any further on this discussion.

**Comment by Tobaloidee** [comment]
Thanks a lot Sir @epicstar i will wait for the discussion.. I made it also an adaptive icon.i will show you here

**Comment by Tobaloidee** [comment]
here is it's adaptive icon version (mock-up)

![ezgif com-crop](https://user-images.githubusercontent.com/36028424/39670171-6fa4df90-5131-11e8-93e7-4d3bab6d80c8.gif)


if there's any suggestions or adjustments that you want to do just let me know Sir and i will edit.

**Comment by Tobaloidee** [comment]
hi Sir @RitwikGupta , if it is okay I can try to combine both layouts if @baligikandasamy and @epicstar  will allow me.

**Comment by RitwikGupta** [comment]
I'm good with that if @baligikandasamy is. I'll reference it in the other issue.

**Comment by Tobaloidee** [comment]
I'll wait for their response Sir before I do it.

**Comment by Tobaloidee** [comment]
Any update Sirs?

**Comment by epicstar** [comment]
Hello, let's wait for @balagikandasamy

**Comment by RitwikGupta** [comment]
I think we should give it a timeout of a week for the other dev to reply. If not, we'll merge this one.

**Comment by Tobaloidee** [comment]
Noted Sir @RitwikGupta

**Comment by balajikandasamy** [comment]
The new icon is good please merge it. I left it after waiting for more than a year.

**Comment by Tobaloidee** [comment]
Thanks for the notice @balajikandasamy  Ill wait for them to say if it's good to make PR and put the files in the repo already..

**Comment by RitwikGupta** [comment]
@Tobaloidee Please make the PR!

**Comment by Tobaloidee** [comment]
Will do Sir!! When I get home 6hrs from now Sir..thanks a lot! :)

**Comment by Tobaloidee** [comment]
Thanks again! will close this now.
