### ISSUE TITLE
Buses sometimes don't disappear when the route is deselected

### ISSUE THREAD

**Issue by mikeantonacci** [rectangle-dbmi/Realtime-Port-Authority#336]
Seems like a timing issue. Need to synchronize the changes to the busicons from the vehicle update observable and the route selection observable. Example logging that demonstrates the issue:

> D/RouteSelection: getting both routes: 61B, [61D, 65]
> D/PatternViewModel$Companion$createPatternSelection: Getting patternSelections: 61B
> D/BusMapFragment$setupReactiveObjects: removing all 61B's
> D/BusMapFragment$setupReactiveObjects: REMOVE 6441: com.google.android.gms.maps.model.Marker@8762692
> D/BusMapFragment$setupReactiveObjects: Iterating through all vehicles to add
> V/BusMapFragment$makeBitmaps: using cached bitmap 61B
> V/BusMapFragment$vehicleUpdateObserver: marker_add adding_marker 6441

**Comment by epicstar** [comment]
This is fixed thank you @mikeantonacci
