### ISSUE TITLE
No Data found

### ISSUE THREAD

**Issue by swb223** [rectangle-dbmi/Realtime-Port-Authority#338]
I was waiting for a 56 bus on Sunday 04/11/2021 for a departure 1:45pm. When i was on the app there was no buses either 61c or 56 can't be found at all. Stating no data could not be found

**Comment by swb223** [comment]
![Capture+_2021-04-11-13-29-57](https://user-images.githubusercontent.com/82332829/114314772-0f8e7e00-9aca-11eb-83b5-b2215292514f.png)

**Comment by swb223** [comment]
There's the document of what was said when getting on the app. As of today

**Comment by timparenti** [comment]
I reached out to Port Authority this afternoon and they confirmed that their TrueTime service, which underlies this app, [is currently experiencing an outage](https://twitter.com/PghTransitCare/status/1381311601727438851).  As such, no app is presently able to pass along real-time data as it simply isn't available.
