### ISSUE TITLE
As of 8/31/21 buses show, but all stops/buses say "no predictions" 

### ISSUE THREAD

**Issue by JarrettBillingsley** [rectangle-dbmi/Realtime-Port-Authority#339]
It was working Monday, but now it's not, and now I cry.

**Comment by JarrettBillingsley** [comment]
I cleared the app data/cache and now the problem is worse - routes no longer appear on the map, just lonely buses floating in a soup of streets. But maybe that's pointing to an underlying problem (route data not available?)

**Comment by epicstar** [comment]
I actually don't see the problem on 8.x of the app... So either the cache mechanism is broken on 7.x or that the route API doesn't support XML anymore. (At least... I think 7.x uses XML while 8.x uses all json). It's been a while. @mikeantonacci is looking into it.

**Comment by bbukh** [comment]
I can confirm the issue in version 7.0.7 of the app (the latest on the Play Store). Where is the version 8.x available from?

**Comment by JarrettBillingsley** [comment]
Glad to see it's being looked into! I was worried the app was abandoned. I'm guessing 8.x is your development version?

**Comment by mikeantonacci** [comment]
Yes. I'm still looking into it, but it does so far seem like it might be
better in 8.x versions.

You actually can get version 8.0.2-beta currently if you want to try that
by switching to the beta release in the Google Play store.

**Comment by JarrettBillingsley** [comment]
I got into the 8.x beta and can confirm it's working!

**Comment by epicstar** [comment]
I promoted the beta to production. That'll fix the immediate issue. There are still issues with routes being partially shown. I've already contacted TrueTime and Port Authority for a fix.

**Comment by JarrettBillingsley** [comment]
It doesn't help that the past few days the buses seem to be having a lot of trouble with their identification/transponders (it's like a third of the buses say WRONG CODE on the LED display, and don't show up on the map at all)

**Comment by epicstar** [comment]
It's been fixed. Please give all credit to @mikeantonacci.

We're doing a hardcoded version of some fields in v3 of the TrueTime API. When time allows, we'll start developing on all the features of the TrueTime v3 API (#322 )

**Comment by ShashankOV** [comment]
Appreciate it! Thanks!
