### ISSUE TITLE
No Tracking Data, No Route Lines/Stops

### ISSUE THREAD

**Issue by Cmsciulli** [rectangle-dbmi/Realtime-Port-Authority#348]
As of yesterday afternoon, the tracking functionality ceased to work.  I received an error that Port Authority's Servers were down.

Checked this morning, and same issue. Tried clearing my routes and route cache and now I have lost all route lines and stops, and there's still no tracking info.

Thanks for your help!

**Comment by epicstar** [comment]
Closing this issue since this is on Port Authority's side. Thanks for bringing this up, and please let me know if you have anymore questions.
